/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DocumentType = IDL.Variant({
  'manifest' : IDL.Null,
  'billOfLading' : IDL.Null,
  'customsDeclaration' : IDL.Null,
});
export const ShipmentStatus = IDL.Variant({
  'customsHold' : IDL.Null,
  'inTransit' : IDL.Null,
  'cleared' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Time = IDL.Int;
export const ActorRole = IDL.Variant({
  'admin' : IDL.Null,
  'customsOfficer' : IDL.Null,
  'shippingLine' : IDL.Null,
  'portAgent' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : ActorRole,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'subject' : IDL.Text,
  'isRead' : IDL.Bool,
  'toRole' : ActorRole,
  'timestamp' : Time,
  'fromRole' : ActorRole,
});
export const DocumentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ReportSummary = IDL.Record({
  'totalMessages' : IDL.Nat,
  'totalShipmentsByStatus' : IDL.Vec(IDL.Tuple(ShipmentStatus, IDL.Nat)),
  'totalDocumentsByStatus' : IDL.Vec(IDL.Tuple(DocumentStatus, IDL.Nat)),
});
export const Document = IDL.Record({
  'id' : IDL.Nat,
  'status' : DocumentStatus,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'shipmentId' : IDL.Nat,
  'docType' : DocumentType,
});
export const Shipment = IDL.Record({
  'id' : IDL.Nat,
  'eta' : Time,
  'vesselName' : IDL.Text,
  'shipper' : IDL.Text,
  'status' : ShipmentStatus,
  'containerNumber' : IDL.Text,
  'destination' : IDL.Text,
  'createdAt' : Time,
  'origin' : IDL.Text,
  'consignee' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDocument' : IDL.Func(
      [DocumentType, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createShipment' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ShipmentStatus,
        IDL.Text,
        Time,
      ],
      [IDL.Nat],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessagesByRole' : IDL.Func([ActorRole], [IDL.Vec(Message)], ['query']),
  'getReports' : IDL.Func([], [ReportSummary], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
  'listMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'listShipments' : IDL.Func([], [IDL.Vec(Shipment)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func(
      [ActorRole, ActorRole, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateDocumentStatus' : IDL.Func([IDL.Nat, DocumentStatus], [], []),
  'updateShipmentStatus' : IDL.Func([IDL.Nat, ShipmentStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DocumentType = IDL.Variant({
    'manifest' : IDL.Null,
    'billOfLading' : IDL.Null,
    'customsDeclaration' : IDL.Null,
  });
  const ShipmentStatus = IDL.Variant({
    'customsHold' : IDL.Null,
    'inTransit' : IDL.Null,
    'cleared' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Time = IDL.Int;
  const ActorRole = IDL.Variant({
    'admin' : IDL.Null,
    'customsOfficer' : IDL.Null,
    'shippingLine' : IDL.Null,
    'portAgent' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : ActorRole });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'subject' : IDL.Text,
    'isRead' : IDL.Bool,
    'toRole' : ActorRole,
    'timestamp' : Time,
    'fromRole' : ActorRole,
  });
  const DocumentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ReportSummary = IDL.Record({
    'totalMessages' : IDL.Nat,
    'totalShipmentsByStatus' : IDL.Vec(IDL.Tuple(ShipmentStatus, IDL.Nat)),
    'totalDocumentsByStatus' : IDL.Vec(IDL.Tuple(DocumentStatus, IDL.Nat)),
  });
  const Document = IDL.Record({
    'id' : IDL.Nat,
    'status' : DocumentStatus,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'shipmentId' : IDL.Nat,
    'docType' : DocumentType,
  });
  const Shipment = IDL.Record({
    'id' : IDL.Nat,
    'eta' : Time,
    'vesselName' : IDL.Text,
    'shipper' : IDL.Text,
    'status' : ShipmentStatus,
    'containerNumber' : IDL.Text,
    'destination' : IDL.Text,
    'createdAt' : Time,
    'origin' : IDL.Text,
    'consignee' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDocument' : IDL.Func(
        [DocumentType, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createShipment' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ShipmentStatus,
          IDL.Text,
          Time,
        ],
        [IDL.Nat],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessagesByRole' : IDL.Func([ActorRole], [IDL.Vec(Message)], ['query']),
    'getReports' : IDL.Func([], [ReportSummary], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
    'listMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'listShipments' : IDL.Func([], [IDL.Vec(Shipment)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func(
        [ActorRole, ActorRole, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateDocumentStatus' : IDL.Func([IDL.Nat, DocumentStatus], [], []),
    'updateShipmentStatus' : IDL.Func([IDL.Nat, ShipmentStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };