/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActorRole = { 'admin' : null } |
  { 'customsOfficer' : null } |
  { 'shippingLine' : null } |
  { 'portAgent' : null };
export interface Document {
  'id' : bigint,
  'status' : DocumentStatus,
  'title' : string,
  'content' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'shipmentId' : bigint,
  'docType' : DocumentType,
}
export type DocumentStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type DocumentType = { 'manifest' : null } |
  { 'billOfLading' : null } |
  { 'customsDeclaration' : null };
export interface Message {
  'id' : bigint,
  'content' : string,
  'subject' : string,
  'isRead' : boolean,
  'toRole' : ActorRole,
  'timestamp' : Time,
  'fromRole' : ActorRole,
}
export interface ReportSummary {
  'totalMessages' : bigint,
  'totalShipmentsByStatus' : Array<[ShipmentStatus, bigint]>,
  'totalDocumentsByStatus' : Array<[DocumentStatus, bigint]>,
}
export interface Shipment {
  'id' : bigint,
  'eta' : Time,
  'vesselName' : string,
  'shipper' : string,
  'status' : ShipmentStatus,
  'containerNumber' : string,
  'destination' : string,
  'createdAt' : Time,
  'origin' : string,
  'consignee' : string,
}
export type ShipmentStatus = { 'customsHold' : null } |
  { 'inTransit' : null } |
  { 'cleared' : null } |
  { 'delivered' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : ActorRole }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDocument' : ActorMethod<
    [DocumentType, string, bigint, string],
    bigint
  >,
  'createShipment' : ActorMethod<
    [string, string, string, string, string, ShipmentStatus, string, Time],
    bigint
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessagesByRole' : ActorMethod<[ActorRole], Array<Message>>,
  'getReports' : ActorMethod<[], ReportSummary>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listDocuments' : ActorMethod<[], Array<Document>>,
  'listMessages' : ActorMethod<[], Array<Message>>,
  'listShipments' : ActorMethod<[], Array<Shipment>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[ActorRole, ActorRole, string, string], bigint>,
  'updateDocumentStatus' : ActorMethod<[bigint, DocumentStatus], undefined>,
  'updateShipmentStatus' : ActorMethod<[bigint, ShipmentStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];