/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Shipment {
    id: bigint;
    eta: Time;
    vesselName: string;
    shipper: string;
    status: ShipmentStatus;
    containerNumber: string;
    destination: string;
    createdAt: Time;
    origin: string;
    consignee: string;
}
export interface Document {
    id: bigint;
    status: DocumentStatus;
    title: string;
    content: string;
    createdAt: Time;
    createdBy: Principal;
    shipmentId: bigint;
    docType: DocumentType;
}
export interface Message {
    id: bigint;
    content: string;
    subject: string;
    isRead: boolean;
    toRole: ActorRole;
    timestamp: Time;
    fromRole: ActorRole;
}
export interface UserProfile {
    name: string;
    role: ActorRole;
}
export interface ReportSummary {
    totalMessages: bigint;
    totalShipmentsByStatus: Array<[ShipmentStatus, bigint]>;
    totalDocumentsByStatus: Array<[DocumentStatus, bigint]>;
}
export enum ActorRole {
    admin = "admin",
    customsOfficer = "customsOfficer",
    shippingLine = "shippingLine",
    portAgent = "portAgent"
}
export enum DocumentStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum DocumentType {
    manifest = "manifest",
    billOfLading = "billOfLading",
    customsDeclaration = "customsDeclaration"
}
export enum ShipmentStatus {
    customsHold = "customsHold",
    inTransit = "inTransit",
    cleared = "cleared",
    delivered = "delivered"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createDocument(docType: DocumentType, title: string, shipmentId: bigint, content: string): Promise<bigint>;
    createShipment(containerNumber: string, origin: string, destination: string, shipper: string, consignee: string, status: ShipmentStatus, vesselName: string, eta: Time): Promise<bigint>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMessagesByRole(role: ActorRole): Promise<Array<Message>>;
    getReports(): Promise<ReportSummary>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listDocuments(): Promise<Array<Document>>;
    listMessages(): Promise<Array<Message>>;
    listShipments(): Promise<Array<Shipment>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(fromRole: ActorRole, toRole: ActorRole, subject: string, content: string): Promise<bigint>;
    updateDocumentStatus(documentId: bigint, newStatus: DocumentStatus): Promise<void>;
    updateShipmentStatus(shipmentId: bigint, newStatus: ShipmentStatus): Promise<void>;
}
import type { ActorRole as _ActorRole, Document as _Document, DocumentStatus as _DocumentStatus, DocumentType as _DocumentType, Message as _Message, ReportSummary as _ReportSummary, Shipment as _Shipment, ShipmentStatus as _ShipmentStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createDocument(arg0: DocumentType, arg1: string, arg2: bigint, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDocument(to_candid_DocumentType_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDocument(to_candid_DocumentType_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
            return result;
        }
    }
    async createShipment(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: ShipmentStatus, arg6: string, arg7: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createShipment(arg0, arg1, arg2, arg3, arg4, to_candid_ShipmentStatus_n5(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createShipment(arg0, arg1, arg2, arg3, arg4, to_candid_ShipmentStatus_n5(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessagesByRole(arg0: ActorRole): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessagesByRole(to_candid_ActorRole_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessagesByRole(to_candid_ActorRole_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReports(): Promise<ReportSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getReports();
                return from_candid_ReportSummary_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReports();
            return from_candid_ReportSummary_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listDocuments(): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDocuments();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDocuments();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMessages();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMessages();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async listShipments(): Promise<Array<Shipment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listShipments();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listShipments();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessage(arg0: ActorRole, arg1: ActorRole, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(to_candid_ActorRole_n14(this._uploadFile, this._downloadFile, arg0), to_candid_ActorRole_n14(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(to_candid_ActorRole_n14(this._uploadFile, this._downloadFile, arg0), to_candid_ActorRole_n14(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async updateDocumentStatus(arg0: bigint, arg1: DocumentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDocumentStatus(arg0, to_candid_DocumentStatus_n39(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDocumentStatus(arg0, to_candid_DocumentStatus_n39(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateShipmentStatus(arg0: bigint, arg1: ShipmentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShipmentStatus(arg0, to_candid_ShipmentStatus_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShipmentStatus(arg0, to_candid_ShipmentStatus_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ActorRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActorRole): ActorRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_DocumentStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentStatus): DocumentStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_DocumentType_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentType): DocumentType {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Document_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Document): Document {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ReportSummary_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportSummary): ReportSummary {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_ShipmentStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShipmentStatus): ShipmentStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Shipment_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Shipment): Shipment {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    subject: string;
    isRead: boolean;
    toRole: _ActorRole;
    timestamp: _Time;
    fromRole: _ActorRole;
}): {
    id: bigint;
    content: string;
    subject: string;
    isRead: boolean;
    toRole: ActorRole;
    timestamp: Time;
    fromRole: ActorRole;
} {
    return {
        id: value.id,
        content: value.content,
        subject: value.subject,
        isRead: value.isRead,
        toRole: from_candid_ActorRole_n10(_uploadFile, _downloadFile, value.toRole),
        timestamp: value.timestamp,
        fromRole: from_candid_ActorRole_n10(_uploadFile, _downloadFile, value.fromRole)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalMessages: bigint;
    totalShipmentsByStatus: Array<[_ShipmentStatus, bigint]>;
    totalDocumentsByStatus: Array<[_DocumentStatus, bigint]>;
}): {
    totalMessages: bigint;
    totalShipmentsByStatus: Array<[ShipmentStatus, bigint]>;
    totalDocumentsByStatus: Array<[DocumentStatus, bigint]>;
} {
    return {
        totalMessages: value.totalMessages,
        totalShipmentsByStatus: from_candid_vec_n21(_uploadFile, _downloadFile, value.totalShipmentsByStatus),
        totalDocumentsByStatus: from_candid_vec_n25(_uploadFile, _downloadFile, value.totalDocumentsByStatus)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _DocumentStatus;
    title: string;
    content: string;
    createdAt: _Time;
    createdBy: Principal;
    shipmentId: bigint;
    docType: _DocumentType;
}): {
    id: bigint;
    status: DocumentStatus;
    title: string;
    content: string;
    createdAt: Time;
    createdBy: Principal;
    shipmentId: bigint;
    docType: DocumentType;
} {
    return {
        id: value.id,
        status: from_candid_DocumentStatus_n27(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        shipmentId: value.shipmentId,
        docType: from_candid_DocumentType_n32(_uploadFile, _downloadFile, value.docType)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    eta: _Time;
    vesselName: string;
    shipper: string;
    status: _ShipmentStatus;
    containerNumber: string;
    destination: string;
    createdAt: _Time;
    origin: string;
    consignee: string;
}): {
    id: bigint;
    eta: Time;
    vesselName: string;
    shipper: string;
    status: ShipmentStatus;
    containerNumber: string;
    destination: string;
    createdAt: Time;
    origin: string;
    consignee: string;
} {
    return {
        id: value.id,
        eta: value.eta,
        vesselName: value.vesselName,
        shipper: value.shipper,
        status: from_candid_ShipmentStatus_n23(_uploadFile, _downloadFile, value.status),
        containerNumber: value.containerNumber,
        destination: value.destination,
        createdAt: value.createdAt,
        origin: value.origin,
        consignee: value.consignee
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _ActorRole;
}): {
    name: string;
    role: ActorRole;
} {
    return {
        name: value.name,
        role: from_candid_ActorRole_n10(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_tuple_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_ShipmentStatus, bigint]): [ShipmentStatus, bigint] {
    return [
        from_candid_ShipmentStatus_n23(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_tuple_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_DocumentStatus, bigint]): [DocumentStatus, bigint] {
    return [
        from_candid_DocumentStatus_n27(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    customsOfficer: null;
} | {
    shippingLine: null;
} | {
    portAgent: null;
}): ActorRole {
    return "admin" in value ? ActorRole.admin : "customsOfficer" in value ? ActorRole.customsOfficer : "shippingLine" in value ? ActorRole.shippingLine : "portAgent" in value ? ActorRole.portAgent : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customsHold: null;
} | {
    inTransit: null;
} | {
    cleared: null;
} | {
    delivered: null;
}): ShipmentStatus {
    return "customsHold" in value ? ShipmentStatus.customsHold : "inTransit" in value ? ShipmentStatus.inTransit : "cleared" in value ? ShipmentStatus.cleared : "delivered" in value ? ShipmentStatus.delivered : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): DocumentStatus {
    return "pending" in value ? DocumentStatus.pending : "approved" in value ? DocumentStatus.approved : "rejected" in value ? DocumentStatus.rejected : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manifest: null;
} | {
    billOfLading: null;
} | {
    customsDeclaration: null;
}): DocumentType {
    return "manifest" in value ? DocumentType.manifest : "billOfLading" in value ? DocumentType.billOfLading : "customsDeclaration" in value ? DocumentType.customsDeclaration : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_ShipmentStatus, bigint]>): Array<[ShipmentStatus, bigint]> {
    return value.map((x)=>from_candid_tuple_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_DocumentStatus, bigint]>): Array<[DocumentStatus, bigint]> {
    return value.map((x)=>from_candid_tuple_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Document>): Array<Document> {
    return value.map((x)=>from_candid_Document_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Shipment>): Array<Shipment> {
    return value.map((x)=>from_candid_Shipment_n35(_uploadFile, _downloadFile, x));
}
function to_candid_ActorRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActorRole): _ActorRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_DocumentStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentStatus): _DocumentStatus {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_DocumentType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentType): _DocumentType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ShipmentStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShipmentStatus): _ShipmentStatus {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: ActorRole;
}): {
    name: string;
    role: _ActorRole;
} {
    return {
        name: value.name,
        role: to_candid_ActorRole_n14(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActorRole): {
    admin: null;
} | {
    customsOfficer: null;
} | {
    shippingLine: null;
} | {
    portAgent: null;
} {
    return value == ActorRole.admin ? {
        admin: null
    } : value == ActorRole.customsOfficer ? {
        customsOfficer: null
    } : value == ActorRole.shippingLine ? {
        shippingLine: null
    } : value == ActorRole.portAgent ? {
        portAgent: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentType): {
    manifest: null;
} | {
    billOfLading: null;
} | {
    customsDeclaration: null;
} {
    return value == DocumentType.manifest ? {
        manifest: null
    } : value == DocumentType.billOfLading ? {
        billOfLading: null
    } : value == DocumentType.customsDeclaration ? {
        customsDeclaration: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == DocumentStatus.pending ? {
        pending: null
    } : value == DocumentStatus.approved ? {
        approved: null
    } : value == DocumentStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShipmentStatus): {
    customsHold: null;
} | {
    inTransit: null;
} | {
    cleared: null;
} | {
    delivered: null;
} {
    return value == ShipmentStatus.customsHold ? {
        customsHold: null
    } : value == ShipmentStatus.inTransit ? {
        inTransit: null
    } : value == ShipmentStatus.cleared ? {
        cleared: null
    } : value == ShipmentStatus.delivered ? {
        delivered: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
